services:
  chat-app:
    build:
      context: ./ai_companion
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
      - private-api
    env_file:
      - /Users/johngrubbs/dev/DevMyDrive/Projects/ai_companion/.env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules